name: Battleroyale2
version: '${project.version}'
main: net.mochidsuki.corsica.battleroyale2.Battleroyale2
api-version: 1.19
authors: [ CTT ]
description: Corsica's BattleRoyale 2

commands:
  gameround:
    aliases: [gr]
    description: ゲームのラウンド進行状況
    permission: battleroyale2.command.gamelound
    permission-message: Permission denied
    usage:
  brgame:
    aliases: [brg,battleroyalegame]
    description: ゲームのラウンド進行状況
    permission: battleroyale2.command.brg
    permission-message: Permission denied
    usage:
  debugerb:
    description: debug用
    permission: battleroyale2.command.debuger
    permission-message: Permission denied
    usage: Command usage